name: Build and Deploy to GH Pages
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install and Build
      run: |
        npm ci
        npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BASE_BRANCH: develop
        GIT_CONFIG_NAME: Alin Stefan Olaru
        GIT_CONFIG_EMAIL: alinstefanolaru@gmail.com
